In [1]:
import numpy as np

In [2]:
# Create the initial 4x4 matrix
arr = np.array([
    [10, 20, 30, 40],
    [15, 25, 35, 45],
    [27, 29, 37, 48],
    [32, 33, 39, 50]
])

a) Slicing Questions:

In [3]:
# 1. Extract the first row 
first_row = arr[0, :]

In [4]:
# 2. Extract the last column
last_col = arr[:, -1]

In [5]:
# 3. Extract the first two rows and first three columns
top_left = arr[:2, :3]

In [6]:
# 4. Extract all elements from the second row (index 1)
second_row = arr[1, :]

In [7]:
# 5. Extract elements from row index 1 to 3 and column index 1 to 2
# Note: The upper bound is exclusive, so we use 4 to include index 3, and 3 to include index 2
sub_matrix = arr[1:4, 1:3]

In [8]:
print("1. First row:", first_row)
print("2. Last column:", last_col)
print("3. First 2 rows, 3 cols:\n", top_left)
print("4. Second row:", second_row)
print("5. Row idx 1-3, Col idx 1-2:\n", sub_matrix)

1. First row: [10 20 30 40]
2. Last column: [40 45 48 50]
3. First 2 rows, 3 cols:
 [[10 20 30]
 [15 25 35]]
4. Second row: [15 25 35 45]
5. Row idx 1-3, Col idx 1-2:
 [[25 35]
 [29 37]
 [33 39]]


b) Masking (Boolean Indexing) Questions:

In [9]:
# Create a fresh copy of the array so our modifications don't mess up later steps
arr_mask = arr.copy()

In [10]:
# 1. Select all elements greater than 30
greater_than_30 = arr_mask[arr_mask > 30]
print("\n1. Greater than 30:", greater_than_30)


1. Greater than 30: [40 35 45 37 48 32 33 39 50]


In [11]:
# 2. Select all elements that are even numbers
evens = arr_mask[arr_mask % 2 == 0]
print("2. Even numbers:", evens)

2. Even numbers: [10 20 30 40 48 32 50]


In [12]:
# 3. Replace all elements less than 25 with 0
arr_mask[arr_mask < 25] = 0
print("3. After replacing < 25 with 0:\n", arr_mask)

3. After replacing < 25 with 0:
 [[ 0  0 30 40]
 [ 0 25 35 45]
 [27 29 37 48]
 [32 33 39 50]]


In [13]:
# 4. Select elements that are between 20 and 40 (inclusive)
# Using the original 'arr' here so we have the original data to check
between_20_40 = arr[(arr >= 20) & (arr <= 40)]
print("4. Between 20 and 40:", between_20_40)

4. Between 20 and 40: [20 30 40 25 35 27 29 37 32 33 39]


In [14]:
# 5. Replace all elements in the last column greater than 45 with -1
# We use a mask specifically on the last column slice
arr[:, -1][arr[:, -1] > 45] = -1
print("5. After replacing last column > 45 with -1:\n", arr)

5. After replacing last column > 45 with -1:
 [[10 20 30 40]
 [15 25 35 45]
 [27 29 37 -1]
 [32 33 39 -1]]
