In [1]:
import numpy as np

1. Perform Element-wise addition of 2 numpy arrays

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
addition_result = arr1 + arr2
print("Task 1:", addition_result)

Task 1: [11 22 33]


2. Perform multiplication between Matrix and a scalar.

In [4]:
matrix = np.array([[1, 2], [3, 4]])
scalar = 5
scalar_result = matrix * scalar
print("\nTask 2:\n", scalar_result)


Task 2:
 [[ 5 10]
 [15 20]]


3. Create an Identity matrix

In [5]:
# Creates a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\nTask 3:\n", identity_matrix)


Task 3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Convert 1D array to 3D array

In [6]:
# Create a 1D array of 12 numbers
one_d = np.arange(12) 
# Reshape to 3D: 2 'blocks' (depth), 2 rows, 3 columns
three_d = one_d.reshape(2, 2, 3) 
print("\nTask 4:\n", three_d)


Task 4:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


5. Convert float to integer

In [7]:
float_arr = np.array([1.5, 2.7, 3.1])
int_arr = float_arr.astype(int)
print("\nTask 5:", int_arr)


Task 5: [1 2 3]


6. Matrix Generation with one particular value

In [8]:
# Create a 3x3 matrix filled entirely with the number 7
sevens_matrix = np.full((3, 3), 7)
print("\nTask 6:\n", sevens_matrix)


Task 6:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
