In [1]:
import numpy as np

Task 9: 5x5 random integer matrix (1–100) and max/min

In [2]:
# Generate 5x5 matrix with random integers from 1 to 100
random_ints = np.random.randint(1, 101, size=(5, 5))
print("Task 9 Matrix:\n", random_ints)

print("Maximum value:", random_ints.max())
print("Minimum value:", random_ints.min())

Task 9 Matrix:
 [[ 14  99  52  66 100]
 [ 12  96  26 100  21]
 [ 31  72  45  95  28]
 [ 39  85  11  34   4]
 [  6  43   8  46  77]]
Maximum value: 100
Minimum value: 4


Task 10: 4x6 random matrix, row-wise and column-wise sum

In [3]:
# Generate a 4x6 matrix of random decimal numbers
random_matrix = np.random.rand(4, 6)
print("\nTask 10 Matrix:\n", random_matrix)

# Compute sums across axes
row_sums = random_matrix.sum(axis=1)
col_sums = random_matrix.sum(axis=0)

print("Row-wise sum (axis=1):", row_sums)
print("Column-wise sum (axis=0):", col_sums)


Task 10 Matrix:
 [[0.5042309  0.90570037 0.43457863 0.36567191 0.56591867 0.96298862]
 [0.43932724 0.12062068 0.37733769 0.84175364 0.61831742 0.61728479]
 [0.4183155  0.5530079  0.68471016 0.47331825 0.5613864  0.1731069 ]
 [0.16318318 0.33171131 0.50191687 0.32524217 0.99444182 0.82669607]]
Row-wise sum (axis=1): [3.7390891  3.01464146 2.86384512 3.14319141]
Column-wise sum (axis=0): [1.52505681 1.91104027 1.99854336 2.00598597 2.74006431 2.58007637]


Task 11: 3x4 random float matrix, mean across axis 0 and axis 1

In [4]:
# Generate a 3x4 matrix of random floats
# (np.random.rand generates floats by default)
float_matrix = np.random.rand(3, 4)
print("\nTask 11 Matrix:\n", float_matrix)

# Compute means across axes
mean_axis_0 = float_matrix.mean(axis=0) # Mean of each column
mean_axis_1 = float_matrix.mean(axis=1) # Mean of each row

print("Mean across axis 0 (columns):", mean_axis_0)
print("Mean across axis 1 (rows):", mean_axis_1)


Task 11 Matrix:
 [[0.03615365 0.3868624  0.89811783 0.64517462]
 [0.27410112 0.32247812 0.25400484 0.74008451]
 [0.81782716 0.36647198 0.96355983 0.24736323]]
Mean across axis 0 (columns): [0.37602731 0.35860417 0.7052275  0.54420745]
Mean across axis 1 (rows): [0.49157713 0.39766715 0.59880555]
